### PR TITLE
Add ability to fix table view height

### PR DESCRIPTION
**Pull request by okal**

### CODE REVIEW

**Comment by pld** [comment]
do we want this in master right now? Is there an issue that this is attached to?

**Comment by okal** [comment]
@pld It's support work for a Zebra issue.

**Comment by okal** [comment]
We only need it for the linked Zebra PR to be merged.

**Comment by geoffreymuchai** [comment]
@pld since there is a library deployed with this change, DFID Syria can depend on that before this is merged. The problem with this is that rebasing against master has to take into consideration the hatti version that is required by DFID Syria and this will be a pain to maintain.

**Comment by okal** [comment]
We could just merge it, there's no harm. Unless of course, someone deploys the base snapshot without having this code :-)

**Comment by pld** [comment]
Let's merge it in if it won't cause any problems on production

**Pull request merged**
