### PR TITLE
Map zoom fix

### PR DESCRIPTION
**Pull request by royrutto**
- closes https://github.com/onaio/zebra/issues/2644

### CODE REVIEW

**Comment by royrutto** [comment]
@prabhasp You're right, if you had zoomed out to look at a few particular datapoints you loose your zoom position when switching tabs. 

The latest issue on zooming is still happening though https://github.com/onaio/zebra/issues/2644. I tried using an `if-not` condition and to handle but couldn't figure it out much. (Kept reverting to old behavior)

I was testing using https://beta.ona.io/onasupport/925/28152

**Comment by prabhasp** [comment]
Okay, that test case is helpful; especially since some other maps are working fine. I'm investigating this to see I can get any insights... I think it may have to do with datasets that cross the axes (and therefore have both negative and positive values for longitude or latitude; more when I know more.)

**Comment by prabhasp** [comment]
@royrutto Can you check whether this latest change fixes things adequately and merge in if so?

**Comment by royrutto** [comment]
:+1: Thanks @prabhasp . This fixes it.

**Comment by royrutto** [comment]
@prabhasp the fix is breaking on advance compilation with the error below. (See https://preview.ona.io/onasupport/925/28152)

screen shot 2015-08-25 at 2 06 12 pm

**Comment by royrutto** [comment]
seems like we need to add `.getZoom` to leaflet-externs.js

**Pull request merged**
