### PR TITLE
Revert "OO: Undo changes to table page component"

### PR DESCRIPTION
**Pull request by geoffreymuchai**
@okal Reverted as advised in https://github.com/onaio/hatti/pull/120#issuecomment-211870091

### CODE REVIEW

**Comment by okal** [comment]
Did it have the desired effect when you tested it?

**Comment by okal** [comment]
All the code here already underwent CR, so should be good if you can confirm that the behaviour is what you were after.

**Comment by geoffreymuchai** [comment]
@okal works well as we expect 👯

**Comment by okal** [comment]
Awesome. Then I'd just merge it.

**Pull request merged**
