### PR TITLE
Change to table view on forms with no-geodata only if mapview is bein…

### LINKED ISSUE #27: Client side routing breaks Zebra dataview
To reproduce

1. Load dataview for a page that doesn't have a map. (This is the context I've seen it in. It could well be the same on forms with geo data.)
2. Click "Summary Charts".
3. Refresh page.

What you'd expect is to see the charts view rendered, but you instead get the table view. Clicking on the "Summary Charts" does not take you to the page, since, as far as secretary is concerned, you're already there i.e. `#/charts`. You have to click on a different tab first, before clicking on the summary charts tab to see it.

### PR DESCRIPTION
**Pull request by prabhasp**
…g loaded. Fixes #27 @okal assigning to you to verify bugfix and merge.

### CODE REVIEW

**Comment by okal** [comment]
@pp I'll get to this tomorrow. We've got a deadline on a different project ATM.

**Comment by pld** [comment]
bump

**Comment by okal** [comment]
Can no longer compile CLJS on Zebra. Complains of

```
Compiling "resources/public/js/lib/main.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:src/cljs/ona/dataview/details.cljs
```

**Comment by okal** [comment]
Had to do with some changes made to views/details. Merged in a PR from @royrutto that fixed that. Works well.

**Pull request merged**
